# Generated by Django 5.2.15 on 2026-06-09 15:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_auditlog_action'),
        ('ai', '0002_agentchatsession_agentchatmessage_knowledgearticle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsreport',
            name='template',
            field=models.CharField(choices=[('standard_quality', 'Standard quality'), ('funnel_dynamics', 'Funnel dynamics'), ('custom', 'Custom')], max_length=32),
        ),
        migrations.CreateModel(
            name='CustomReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Natural language report description from manager')),
                ('structured_query', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_reports_authored', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_reports', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='analyticsreport',
            name='custom_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='ai.customreport'),
        ),
    ]
