# Generated by Django 5.2.15 on 2026-06-09 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_auditlog_action'),
        ('ai', '0003_alter_analyticsreport_template_customreport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantAiConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key_encrypted', models.TextField(blank=True, default='')),
                ('base_url', models.URLField(blank=True, default='')),
                ('chat_model', models.CharField(blank=True, default='', max_length=128)),
                ('embedding_model', models.CharField(blank=True, default='', max_length=128)),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_config', to='accounts.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceAiConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key_encrypted', models.TextField(blank=True, default='')),
                ('base_url', models.URLField(blank=True, default='')),
                ('chat_model', models.CharField(blank=True, default='', max_length=128)),
                ('embedding_model', models.CharField(blank=True, default='', max_length=128)),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_config', to='accounts.workspace')),
            ],
        ),
    ]
