# Generated by Django 5.2.15 on 2026-06-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0005_knowledgearticle_content_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantaiconfig",
            name="model_tier",
            field=models.CharField(
                blank=True,
                choices=[("free", "Free"), ("standard", "Standard"), ("premium", "Premium")],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="workspaceaiconfig",
            name="model_tier",
            field=models.CharField(
                blank=True,
                choices=[("free", "Free"), ("standard", "Standard"), ("premium", "Premium")],
                default="",
                max_length=16,
            ),
        ),
    ]
