# Generated by Django 5.2.15 on 2026-06-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='content_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
