# Generated by Django 5.2.15 on 2026-06-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_transcription_content_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsource',
            name='config_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='integrationsource',
            name='credentials_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='integrationsource',
            name='external_id',
            field=models.CharField(blank=True, default='', help_text='External account id (e.g. amoCRM subdomain)', max_length=255),
        ),
    ]
