# Generated by Django 5.2.15 on 2026-06-09 22:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_registrationinvite'),
        ('integrations', '0003_p4_external_id_and_crm_credentials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_lead_id', models.CharField(max_length=128)),
                ('client_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('city', models.CharField(blank=True, default='', max_length=128)),
                ('communication_comment', models.TextField(blank=True, default='')),
                ('pipeline_stage', models.CharField(blank=True, default='', max_length=128)),
                ('status_stage', models.CharField(blank=True, default='', max_length=128)),
                ('recording_url', models.URLField(blank=True, default='')),
                ('manager_email', models.CharField(blank=True, default='', max_length=255)),
                ('supervisor_email', models.CharField(blank=True, default='', max_length=255)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_leads', to=settings.AUTH_USER_MODEL)),
                ('integration_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_leads', to='integrations.integrationsource')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_leads', to='accounts.tenant')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_leads', to='accounts.workspace')),
            ],
            options={
                'ordering': ['-synced_at'],
                'unique_together': {('tenant', 'external_lead_id', 'integration_source')},
            },
        ),
    ]
