# Generated by Django 5.2.15 on 2026-06-10 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_registrationinvite'),
        ('integrations', '0004_crmlead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Agent CRM queries scope leads by tenant + employee_id.
        migrations.AddIndex(
            model_name='crmlead',
            index=models.Index(fields=['tenant', 'employee'], name='crmlead_tenant_employee_idx'),
        ),
        # Dashboard/aggregation counts and filters by tenant + pipeline stage.
        migrations.AddIndex(
            model_name='crmlead',
            index=models.Index(fields=['tenant', 'pipeline_stage'], name='crmlead_tenant_pipeline_idx'),
        ),
        # Dashboard/aggregation counts and filters by tenant + status stage.
        migrations.AddIndex(
            model_name='crmlead',
            index=models.Index(fields=['tenant', 'status_stage'], name='crmlead_tenant_status_idx'),
        ),
        # Stale-sync checks and default ordering by tenant + synced_at (desc).
        migrations.AddIndex(
            model_name='crmlead',
            index=models.Index(fields=['tenant', '-synced_at'], name='crmlead_tenant_synced_idx'),
        ),
    ]
