# Generated by Django 5.2.15 on 2026-06-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_manager_auditlog_managerscope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('permission_change', 'Permission change'), ('scope_denied', 'Scope denied'), ('review_create', 'Review create')], max_length=32),
        ),
    ]
