# Generated by Django 5.2.15 on 2026-06-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='external_id',
            field=models.CharField(blank=True, default='', help_text='External system user id (e.g. amoCRM responsible_user_id)', max_length=128),
        ),
    ]
