# Generated by Django 5.2.15 on 2026-06-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_registrationinvite"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationinvite",
            name="expected_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Если указан, регистрация разрешена только с этим email.",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="registrationinvite",
            name="code",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64, unique=True),
        ),
    ]
